### ISSUE TITLE
Hassio - AddOn doesn't start

### ISSUE THREAD

**Issue by vankarl** [flobz/psa_car_controller#162]
Hi,

I installed the addon as described here: [https://github.com/flobz/psacc-ha/tree/main/psacc-ha](https://github.com/flobz/psacc-ha/tree/main/psacc-ha) 
Tried to start, but got the following error message:

_Containerised psa_car_controller loading...
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 8, in <module>
    import web.app
  File "/psa_car_controller/web/app.py", line 3, in <module>
    import dash_bootstrap_components as dbc
ModuleNotFoundError: No module named 'dash_bootstrap_components'_

HASSIO System Info:
## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v7l
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 57.8 GB
disk_used | 21.4 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (2.3.3), AppDaemon 4 (0.6.2), Dropbox Sync (1.3.0), ESPHome (1.19.4), Grafana (7.0.1), InfluxDB (4.1.1), Let's Encrypt (4.11.0), MariaDB (2.1.1), Mosquitto broker (6.0.1), NGINX Home Assistant SSL proxy (3.0.1), Nginx Proxy Manager (0.11.0), Node-RED (9.1.4), Pi-hole (4.0.0), Terminal & SSH (9.1.3), deCONZ (6.9.0), Zigbee2mqtt (1.18.1-1), zigbee2mqttassistant (0.3.157), Portainer (1.5.1), Samba share (9.5.1), PSA Car Controller (v2.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

Please, let me know if you need more details.

**Comment by camuxx86** [comment]
Same problem for me.

Can you confirm also this issue? on the configuration tab, any host ip saved, after the rastart of the component, is dropped to 3 char? 
ex:
192.168.1.x --> 192

**Comment by italoc** [comment]
In this tab you need to put the port if you want a port different of 5000 not the host IP

**Comment by camuxx86** [comment]
> In this tab you need to put the port if you want a port different of 5000 not the host IP

Really? Since I had read "host", I thought was an IP host not a tcp port...

Anyway I leave it blank...

**Comment by vankarl** [comment]
Yeah, it's the port on the host as the first one is the port on the container.
And I think it's disabled, when you leave it blank. At least that's what it says for me.

Anyway, I found this: [https://stackoverflow.com/questions/60021936/dash-bootstrap-components-installed-succesfully-but-no-recognised](https://stackoverflow.com/questions/60021936/dash-bootstrap-components-installed-succesfully-but-no-recognised)

Might this help?

**Comment by italoc** [comment]
> And I think it's disabled, when you leave it blank. At least that's what it says for me.


No, if you leave it blank use default port 5000

**Comment by show2go** [comment]
Hello,
i have the same problem, addon not starting
log:
Containerised psa_car_controller loading...
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 8, in <module>
    import web.app
  File "/psa_car_controller/web/app.py", line 3, in <module>
    import dash_bootstrap_components as dbc
ModuleNotFoundError: No module named 'dash_bootstrap_components'

thx

**Comment by davidjesse** [comment]
Same issue here.

I saw that in requirements.txt the dependency is listed as `dash_bootstrap_components` (with underscores) but wouldn't it be `dash-bootstrap-components` (with hyphens) instead as that seems to be the library name?

Thanks!!

**Comment by flobz** [comment]
I should be fixed now. Uninstall and reinstall the app.

**Comment by camuxx86** [comment]
Yes It's working now... Thanks flobz

**Comment by show2go** [comment]
Im Sorry, but for me it doesnt work...
i have a RPI3B with HomeassistantOS... and latest updates
i did uninstall, restart server, refresh the repositorys and install it again,
but still the same failure at start of the addon..

**Comment by vankarl** [comment]
It isn't working for me either.
Do I have to do anything beyond what @show2go described?

**Comment by Flodu31** [comment]
Hi Flobz,
Doesn't work for me too, on Hass.io 6.1.
Version core-2021.6.6, supervisor supervisor-2021.06.6.
Thanks.
Florent

**Comment by camuxx86** [comment]
For me It's all ok... I've the last version of hassos and core.
Maybe we have different python packages installed...

**Comment by flobz** [comment]
This problem depends of the processor arch. I forgot to update hassio addons repos. Now you should be able to update the addons and the new version should fixed the problem.

**Comment by Flodu31** [comment]
Hello, 
Thanks flobz, it starts now.
I have another error, I'll open another feed:

```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

**Comment by flobz** [comment]
Should be fixed with new version v2.4.2

**Comment by Flodu31** [comment]
Works fine for me thanks.
Any idea on how to restore a db from another server? Thanks.
Florent

**Comment by flobz** [comment]
The db should be available in the host server. Just replace it. I don't remember the path sorry.

**Comment by Flodu31** [comment]
Ok Thanks, I'll search.
I tried also to access the api like this http://localhost:5000/get_vehicleinfo/YOURVIN but directly in home assistant. And I have no return, is it working on your side?
Thanks.
Florent

**Comment by vankarl** [comment]
It works now. Thank you!

**Comment by Flodu31** [comment]
> The db should be available in the host server. Just replace it. I don't remember the path sorry.

I did the trick. The data folder is located here, on the HA host: /mnt/data/supervisor/addons/data/b9f12d83_psacc/
I did a stop, replace the info.db file by the file that I get from my preivous server, started it back, and it works.

Last point that I need to tackle, is to query the API of this new integration.
